My:
  Site:
    example: test

Neos:
  Fusion:
    defaultContext:
      Joke: 'My\Site\Eel\JokeHelper'
  Neos:
    userInterface:
      translation:
        autoInclude:
          My.Site:
            - 'NodeTypes/*'
